### ISSUE TITLE
For loop initial declaration used outside C99 mode during install

### ISSUE THREAD

**Issue by ghost** [hadley/plyr#126]
This may be an easy fix, but I am unsure what to do here.  I am installing plyr (just as I have installed countless other packages), but I am running into an error with a variable declaration during the install.  I know how to set gcc to c99 mode, but unsure how I would force the R installer to go through those processes.
If someone could provide some insight on this that would be great.

Here is the entire script of the install

sudo R CMD INSTALL plyr_1.8.tar.gz 
installing to library ‘/Developer/lib/R/site-library’
installing _source_ package ‘plyr’ ...
package ‘plyr’ successfully unpacked and MD5 sums checked
libs

flag-sort -r gcc -I/Developer/Library/Frameworks/R.framework/Versions/2.15/Resources/include -DNDEBUG  -I/Developer/include    -fPIC  -g -O2  -c loop-apply.c -o loop-apply.o
loop-apply.c: In function ‘loop_apply’:
loop-apply.c:15: error: ‘for’ loop initial declaration used outside C99 mode
make: **\* [loop-apply.o] Error 1

ERROR: compilation failed for package ‘plyr’
removing ‘/Developer/lib/R/site-library/plyr’
restoring previous ‘/Developer/lib/R/site-library/plyr’

**Comment by tshicelg** [comment]
Saw this problem again.  Tried both 1.8.4 and 1.8.5.  Same error.

> install.packages("../../Downloads/plyr_1.8.4.tar.gz")
Installing package into \u2018/mnt/netapp/home/Tshi/R/R_3.6\u2019
(as \u2018lib\u2019 is unspecified)
inferring 'repos = NULL' from 'pkgs'
* installing *source* package \u2018plyr\u2019 ...
** package \u2018plyr\u2019 successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/mnt/netapp/home/Tshi/R/R_3.6/Rcpp/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c RcppExports.cpp -o RcppExports.o
gcc -m64 -I"/usr/include/R" -DNDEBUG  -I"/mnt/netapp/home/Tshi/R/R_3.6/Rcpp/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c loop_apply.c -o loop_apply.o
loop_apply.c: In function \u2018loop_apply_\u2019:
loop_apply.c:15:3: error: \u2018for\u2019 loop initial declarations are only allowed in C99 mode
   for(int i = 0; i < n1; i++) {
   ^
loop_apply.c:15:3: note: use option -std=c99 or -std=gnu99 to compile your code
make: *** [loop_apply.o] Error 1
ERROR: compilation failed for package \u2018plyr\u2019
* removing \u2018/mnt/netapp/home/Tshi/R/R_3.6/plyr\u2019
Warning message:
In install.packages("../../Downloads/plyr_1.8.4.tar.gz") :
  installation of package \u2018../../Downloads/plyr_1.8.4.tar.gz\u2019 had non-zero exit status

> library(Rcpp)

> install.packages("plyr")
Installing package into \u2018/mnt/netapp/home/Tshi/R/R_3.6\u2019
(as \u2018lib\u2019 is unspecified)
trying URL 'https://ftp.osuosl.org/pub/cran/src/contrib/plyr_1.8.5.tar.gz'
Content type 'application/x-gzip' length 394424 bytes (385 KB)
==================================================
downloaded 385 KB

* installing *source* package \u2018plyr\u2019 ...
** package \u2018plyr\u2019 successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/mnt/netapp/home/Tshi/R/R_3.6/Rcpp/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c RcppExports.cpp -o RcppExports.o
gcc -m64 -I"/usr/include/R" -DNDEBUG  -I"/mnt/netapp/home/Tshi/R/R_3.6/Rcpp/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c loop_apply.c -o loop_apply.o
loop_apply.c: In function \u2018loop_apply_\u2019:
loop_apply.c:15:3: error: \u2018for\u2019 loop initial declarations are only allowed in C99 mode
   for(int i = 0; i < n1; i++) {
   ^
loop_apply.c:15:3: note: use option -std=c99 or -std=gnu99 to compile your code
make: *** [loop_apply.o] Error 1
ERROR: compilation failed for package \u2018plyr\u2019
* removing \u2018/mnt/netapp/home/Tshi/R/R_3.6/plyr\u2019

The downloaded source packages are in
	\u2018/tmp/RtmpB838V8/downloaded_packages\u2019
Warning message:
In install.packages("plyr") :
  installation of package \u2018plyr\u2019 had non-zero exit status

> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rcpp_1.0.3

loaded via a namespace (and not attached):
 [1] pillar_1.4.2         compiler_3.6.1       tools_3.6.1         
 [4] zeallot_0.1.0        digest_0.6.22        bit_1.1-14          
 [7] lattice_0.20-38      RSQLite_2.2.0        memoise_1.1.0       
[10] tibble_2.1.3         lifecycle_0.1.0      gtable_0.3.0        
[13] pkgconfig_2.0.3      rlang_0.4.4          Matrix_1.2-17       
[16] fastmatch_1.1-0      DBI_1.1.0            parallel_3.6.1      
[19] gridExtra_2.3        fgsea_1.10.1         dplyr_0.8.4         
[22] vctrs_0.2.0          S4Vectors_0.22.0     IRanges_2.18.0      
[25] tidyselect_1.0.0     stats4_3.6.1         bit64_0.9-7         
[28] grid_3.6.1           glue_1.3.1           Biobase_2.44.0      
[31] data.table_1.12.6    R6_2.4.0             AnnotationDbi_1.46.0
[34] tcltk_3.6.1          BiocParallel_1.18.1  GOSemSim_2.10.0     
[37] purrr_0.3.3          magrittr_1.5         GO.db_3.8.2         
[40] DO.db_2.9            ggplot2_3.2.1        blob_1.2.0          
[43] backports_1.1.5      scales_1.1.0         BiocGenerics_0.30.0 
[46] assertthat_0.2.1     colorspace_1.4-1     lazyeval_0.2.2      
[49] munsell_0.5.0        crayon_1.3.4
