### ISSUE TITLE
R exception when data frame has strptime output

### ISSUE THREAD

**Issue by jpritikin** [hadley/plyr#132]
Error in attributes(out) <- attributes(col) : 
  'names' attribute [9] must be the same length as the vector [1]

Reproduce with:

  df <- expand.grid(factor(1:5))
  dates <- c("02/27/92", "02/27/92", "01/14/92", "02/28/92", "02/01/92")
  times <- c("23:03:20", "22:29:56", "01:03:30", "18:21:03", "16:56:26")
  df$tm <- strptime(paste(dates, times), "%m/%d/%y %H:%M:%S")
  attributes(df$tm)
  ddply(df, ~Var1, dim)

**Comment by dioh** [comment]
Hi all, I have the same problems but no date values. Any clues?
