### ISSUE TITLE
`here` in plyr conflicts with `here` in lubridate

### ISSUE THREAD

**Issue by dougmitarotonda** [hadley/plyr#157]
lubridate and plyr permeate all of the work I do. Since plyr v1.8, `here` is now defined in both lubridate and plyr, and hence I see warning messages on replacing the previous import. I understand that uniqueness is not required and there are only so many function names to go around, but because both lubridate and plyr are maintained by the same people, I was wondering if it makes sense to name one of the functions differently.

**Comment by derrickoswald** [comment]
This is sad.
