### ISSUE TITLE
Inconsistent output for raply

### ISSUE THREAD

**Issue by krlmlr** [hadley/plyr#167]
```
> raply(0, 1)
logical(0)
> raply(1, 1)
1 
1 
> raply(2, 1)
[1] 1 1
> raply(3, 1)
[1] 1 1 1
> dput(raply(1, 1))
structure(1, .Names = "1")
```

What is so special about the case `.n == 1` in `raply`? Other functions that use `list_to_array` might be affected, too.

**Comment by hadley** [comment]
I think this is sufficiently confusing that I'll never have enough time to fully grok the issue, and it's such a small corner case, I don't think it's worth fixing (at the risk of breaking existing cran code)
