### ISSUE TITLE
.id parameter for adply?

### ISSUE THREAD

**Issue by krlmlr** [hadley/plyr#191]
Similar to #188, as suggested there.

```s
> adply(matrix(1:4, nrow=2), 2, function(a) data.frame(a=a))
  X1 a
1  1 1
2  1 2
3  2 3
4  2 4
> adply(matrix(1:4, nrow=2), 1:2, function(a) data.frame(a=a))
  X1 X2 a
1  1  1 1
2  2  1 2
3  1  2 3
4  2  2 4
```

Dimension names would do better here (see #190), but an `.id` parameter could be used to specify a replacement for `X` or to drop these columns altogether.

**Comment by hadley** [comment]
I'd consider a pull request for this. (But needs to be in the next week or so)

**Comment by krlmlr** [comment]
I'll take a look. Are you interested in adding coverage analysis and linting?

**Comment by hadley** [comment]
No, because I'd be horrified!
