### ISSUE TITLE
Warining "... may be used in an incorrect context: ‘.fun(piece, ...)’" in plyr using parallel

### ISSUE THREAD

**Issue by renkun-ken** [hadley/plyr#203]
This package is terrific! But when I call `**ply` functions with parallel computing, warnings of `... may be used in an incorrect context: ‘.fun(piece, ...)’` always occur.
Here's a simple reproducible code:

```r
require(doParallel)
cl <- makeCluster(2)
registerDoParallel(cl)

l1 <- as.list(1:1000)
require(plyr)
d2 <- ldply(l1,function(i) {
  return(data.frame(x=rnorm(100)+i))
}, .parallel=T)

stopCluster(cl)
```

Each time when I set `.parallel=T` to use the local two-node cluster, the computing finishes but with 2 warnings:

```
Warning messages:
1: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
2: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
```

If I don't enable `.parallel=T` and use sequential computing, the warnings do not appear.

The same thing happens to `ddply()` too. Here's another example:

```r
df <- data.frame(i=1:100,id=sample(LETTERS[1:5],100,replace=T),
  cls=sample(LETTERS[1:5],100,replace=T),x=rbinom(100,10,0.5),
  y=rbinom(100,10,0.5))
d4 <- ddply(df,.(i),function(row) {
  return(row)
}, .parallel=T)
```

The two warnings occurs too.
I don't get very useful information online. What's the problem here?

**Comment by hadley** [comment]
I think this is fixed in the main branch now

**Comment by bornakke** [comment]
The bug seem to be back in plyr version 1.8.3. @renkun-ken code and similar request yields the same two warnings. 

cl <- makeCluster(2)
registerDoParallel(cl)

l1 <- as.list(1:1000)
require(plyr)
d2 <- ldply(l1,function(i) {
  return(data.frame(x=rnorm(100)+i))
}, .parallel=T)

stopCluster(cl)

**Comment by buggythepirate** [comment]
It didn't work in plyr version 1.8.2 either. I tried both doSnow and doParallel both showed the same message as above.

**Comment by ralfer** [comment]
Still does not work in plyr 1.8.3

**Comment by Nosferican** [comment]
Still does not work in plyr 1.8.4

**Comment by touala** [comment]
I don't have too much time to look more closely but I saw two distinct behavior 
```
library(doParallel)
library(doSNOW)
library(plyr)
df <- data.frame(val=1:10, ind=c(rep(2, 5), rep(3, 5)))
```

```
registerDoParallel(2)
system.time(print(ddply(df, .(ind), function(x) { Sys.sleep(2); sum(x) }, .parallel=TRUE)))
registerDoSEQ()
```
Works properly.
```
cl <- makeCluster(2, type="SOCK")
registerDoParallel(cl)
system.time(print(ddply(df, .(ind), function(x) { Sys.sleep(2); sum(x) }, .parallel=TRUE)))
Warning messages:
1: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
2: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
stopCluster(cl)
```
Return a warning. Hope it will help.

**Comment by Deleetdk** [comment]
@hadley @krlmlr Bug still present here 5 years later (still same version 1.8.4). Is the plan that you want for a community pull request or how do we get this fixed? IMO **plyr** is superior to **dplyr** for some tasks (e.g. `ddply` with 2 groups), so I rely on some **plyr** calls and get this warning.
