### ISSUE TITLE
aaply takes forever on simple case

### ISSUE THREAD

**Issue by hadley** [hadley/plyr#212]
```R
plyr::aaply(mtcars, 1, mean)
```

**Comment by krlmlr** [comment]
`mapply` passes a data frame to `aaply`, but this use case still is rare. The only robust solution I see is to invent a new argument `.dataframe_ok` that defaults to `FALSE` and can be overridden by `mapply` (or other users of this scenario).

@hadley: Shall we try this and be ready to revert if too many CRAN packages start failing?

**Comment by hadley** [comment]
I'm not interested in any major changes at this point.

**Comment by krlmlr** [comment]
This is just a new argument with a sensible default value and two lines of code that act on this argument. Potentially breaking, yes, but I wouldn't call it a major change...

Would you review a pull request if the revdep check succeeds?

**Comment by hadley** [comment]
@krlmlr to be honest, I'd prefer not to - I just don't have the brain space to do a good job of it.
