### ISSUE TITLE
Segfault with ddply (plyr 1.8.1)

### ISSUE THREAD

**Issue by lionel-** [hadley/plyr#214]
I was trying to modify position_dodge in ggplot2 when I got R crashing with a segfault.
I tracked it down to a ddply call. It occurs when you fail to correctly pass the arguments of the "strategy" function. 

Steps to reproduce:

```
strategy <- function(df, height) {
  n <- length(unique(df$group))
  if (n == 1) return(df)

  if (!all(c("ymin", "ymax") %in% names(df))) {
      df$ymin <- df$y
      df$ymax <- df$y
  }

  d_width <- max(df$ymax - df$ymin)
  diff <- height - d_width

  # Have a new group index from 1 to number of groups.
  # This might be needed if the group numbers in this set don't include all of 1:n
  groupidx <- match(df$group, sort(unique(df$group)))

  # Find the center for each group, then use that to calculate xmin and xmax
  df$y <- df$y + height * ((groupidx - 0.5)/n - 0.5)
  df$ymin <- df$y - d_width / n / 2
  df$ymax <- df$y + d_width / n / 2

  df
}

test <- data.frame(x = letters[1:4], y = 1:4)
ddply(test, "x", strategy)
```

**Comment by mohitr** [comment]
getting same error again and again and reproducible also.

 *** caught segfault ***
address 0x7f7de00000a6, cause 'memory not mapped'

Traceback:
 1: row.names(x)
 2: write.table(y, file = "y.csv", col.names = NA, sep = ",", dec = ".",     qmethod = "double")
 3: eval(expr, envir, enclos)
 4: eval(expr, p)
 5: eval.parent(Call)
 6: write.csv(y, file = "y.csv")

@lionel- by any chance you were able to figure out reason for this ?

**Comment by lionel-** [comment]
@mohitr sorry, I don't remember. I guess you tried upgrading R and reinstalling packages?

your traceback is weird, I don't see any plyr command in it
