### ISSUE TITLE
mdply with parallel=T and paropts(.export=) gives error

### ISSUE THREAD

**Issue by tentacles-from-outer-space** [hadley/plyr#215]
I suspect this is not desired behavior.

Setup:

    require(plyr) && require(doParallel)
    registerDoParallel(3)
    pars <- data.frame(a=1:3,b=LETTERS[1:3])
    X <- letters

And now: no parallel works

    mdply(pars, function(a, b) paste(X[a],b,sep=":"))
parallel fails cause `X` is object from the current session:

    mdply(pars, function(a, b) paste(X[a],b,sep=":"), .parallel=TRUE)
    # Error in do.ply(i) : task 1 failed - "object 'X' not found"
So next should work, but it doesn't

    mdply(pars, function(a, b) paste(X[a],b,sep=":")
          ,.parallel=TRUE, .paropts=list(.export="X"))
    # Error in do.ply(i) : task 1 failed - "object 'X' not found"

But cutting part of `mdply` function works as supposed to be:

    adply(pars, 1, function(x) paste(X[x$a],x$b,sep=":")
          ,.parallel=TRUE, .paropts=list(.export="X"))

I can't figure it out. Seems that something with passing arguments is not working (`flat`?).

**Comment by hadley** [comment]
Yeah, unfortunately `splat()` was written before I understood this stuff well. It's unlikely to ever get fixed because it would require a lot of thinking, and I'm now working on dplyr instead.
