### ISSUE TITLE
`splat` suffers from lazy evaluation

### ISSUE THREAD

**Issue by tentacles-from-outer-space** [hadley/plyr#217]
The following:

    f <- function(a) a+1
    sf <- splat(f)
    rm(f)
    sf(1)
    Error in do.call(flat, c(args, list(...))) : object 'f' not found

could be suppresed by using `force`:

    splat <- function (flat) {
    	force(flat)
    	function(args, ...)  do.call(flat, c(args, list(...)))
    }

**Comment by hadley** [comment]
Yeah, unfortunately plyr doesn't do NSE right (and it never will)
