### ISSUE TITLE
mutating the same column twice doesn't work

### ISSUE THREAD

**Issue by krlmlr** [hadley/plyr#218]
Compare:

```
library(magrittr)
iris %>%
  mutate(
    Sepal.Length = as.character(Sepal.Length),
    Sepal.Length = as.numeric(Sepal.Length)) %>%
  summary
iris %>%
  mutate(Sepal.Length = as.character(Sepal.Length)) %>%
  mutate(Sepal.Length = as.numeric(Sepal.Length)) %>%
  summary
```

The fix is straightforward, but can we afford fixing this issue at all? This seems to be already fixed in `dplyr`: https://github.com/hadley/dplyr/blob/master/tests/testthat/test-mutate.r .

**Comment by hadley** [comment]
Closing, since `mutate()` development has shifted to dplyr
