### ISSUE TITLE
llply (and others) on unnamed character vector could use input as names (like sapply)

### ISSUE THREAD

**Issue by DarwinAwardWinner** [hadley/plyr#219]
In base R, the `sapply` function has this bit of code after the call to `lapply`:

    if (USE.NAMES && is.character(X) && is.null(names(answer))) 
        names(answer) <- X

This uses the input as the names for the output, but only if no other names are available. I think `llply`, `laply`, and any other relevant functions could easily do likewise.

**Comment by hadley** [comment]
This behaviour has caused me a lot of frustration, so it's unlikely to be included in plyr.

**Comment by DarwinAwardWinner** [comment]
That's ok. Now that magrittr is a thing I can do this to get what I want: `x %>% setNames(.) %>% lapply(...)`
