### ISSUE TITLE
change error message for summarize to hint at shadowed functions

### ISSUE THREAD

**Issue by zachcp** [hadley/plyr#220]
I just spent some time trying to fix a function that wasn't broken becasue `plyr`'s summarize functoin was  shadowing `dplyr`s. Grrr.... I was doing something like this:

```R
#my input
df %>%
  group_by(col1,col2) %>%
  summarize(size=n())
#the output error message
Error in n() : This function should not be called directly
```

Any chance you could write in an error message like this one:
`Error in n() : This function should not be called directly. Perhaps you want dplyr::summarize instead? `

It might be useful for any error function that could clash directly with dplyr especially as people are using both.  
Thanks for some great packages.

zach cp

p.s. Not sure why the function was shadowed as I imported `ply`r and then `dplyr` but i am using `dplyr::summarize` to be safe.

**Comment by hadley** [comment]
I think this is a dplyr buglet

**Comment by abiyug** [comment]
Just saw the same issue:
```
> us_accident %>% group_by(make, model) %>% summarise(count = n()) %>% arrange(desc(count))
_Error in n() : This function should not be called directly_
```

**works:** 
`us_accident %>% group_by(make, model) %>% dplyr::summarise(count = n()) %>% arrange(desc(count))
`

**dplyr version 0.5.0**
```
sessionInfo(package = "dplyr")
R version 3.3.1 (2016-06-21)

attached base packages:
character(0)

other attached packages:
[1] dplyr_0.5.0
```

**Comment by scarrera11** [comment]
I'm having a similar issue. When trying to use summarise_all() I get the error "This function should not be directly called." However, it works fine if I just use summarise. 

Error:
rank_data %>%
  group_by(unit, Rank_Year, Rank_Month) %>%
  dplyr::summarise_all(n())

Works:
rank_data %>%
  group_by(unit, Rank_Year, Rank_Month) %>%
  dplyr::summarise(n())


Thanks for any help!
