### ISSUE TITLE
rbind.fill erases second of duplicate column names

### ISSUE THREAD

**Issue by ajdamico** [hadley/plyr#221]
should this at least warn the user? :)  thanks hadley

	library(plyr)

	a <- data.frame( one = 1 , one = 2 )

	rbind( a , a )
	rbind.fill( a , a )	# works the same

	names( a )[ 2 ] <- 'one'

	rbind( a , a )		# maintains two separate columns
	rbind.fill( a , a ) 	# erases the second column without a warning

**Comment by hadley** [comment]
Since all `rbind.fill` equivalent development is now happening in dplyr, and this is technically an invalid data frame, I'm going to close.
