### ISSUE TITLE
rbind.fill behaves differently from rbind when columns have missing names

### ISSUE THREAD

**Issue by ajdamico** [hadley/plyr#223]
library(plyr)

	y <- x <- data.frame( a = 1:4 , b = 3 , c = 2:3 )

	names( x )[ 2 ] <- names( y )[ 2 ] <- NA

	# different results
	rbind( x , y )		# works
	rbind.fill( x , y )	# error

	# but if you change rbind.fill behavior,
	# what should happen here?
	names( y )[ 3 ] <- NA
	rbind( x , y )
	rbind.fill( x , y )

**Comment by hadley** [comment]
Closing, since all equivalent development is now happening in dplyr
