### ISSUE TITLE
x_ply functions raise error when argument is of length 0 and .progress="text"

### ISSUE THREAD

**Issue by nathanielguy** [hadley/plyr#227]
The x_ply functions raise an error when the argument is of length 0 and .progress is set to "text".  The xxply functions do not raise this error.

Example:
````r
l_ply(numeric(), length)
# No error

l_ply(numeric(), .progress="text", length)
# Error in txtProgressBar(max = x, style = style, ...): must have 'max' > 'min'

llply(numeric(), .progress="text", length)
# No error
````

**Comment by hadley** [comment]
This is going to be fiddly to fix, it's an unusual corner case and plyr isn't being actively developed, so I'm just going to close this issue.
