### ISSUE TITLE
Which `plyr` functions drop `row.names` and which don't?

### ISSUE THREAD

**Issue by landroni** [hadley/plyr#232]
The `plyr` manual states this: 

> By design, no plyr function will preserve row names - in general it is too hard to know what should
be done with them for many of the operations supported by plyr.

However, this clearly does NOT apply to all `plyr` functions. For instance, `arrange` drops row names, as per its help page: 

> NOTE: plyr functions do NOT preserve row.names

    require(plyr)
    data(mtcars)
    > head(arrange(mtcars, cyl, disp))
       mpg cyl  disp       hp drat    wt  qsec vs am gear carb
    1 33.9   4  71.1 4.189655 4.22 1.835 19.90  1  1    4    1
    2 30.4   4  75.7 3.970292 4.93 1.615 18.52  1  1    4    2
    3 32.4   4  78.7 4.204693 4.08 2.200 19.47  1  1    4    1
    4 27.3   4  79.0 4.204693 4.08 1.935 18.90  1  1    4    1
    5 30.4   4  95.1 4.736198 3.77 1.513 16.90  1  1    5    2
    6 22.8   4 108.0 4.543295 3.85 2.320 18.61  1  1    4    1

But `mutate` doesn't (and its help page says nothing about `row.names`): 

    > head(mutate(mtcars, hp = log(hp + 1)))
                       mpg cyl disp       hp drat    wt  qsec vs am gear carb
    Mazda RX4         21.0   6  160 1.742137 3.90 2.620 16.46  0  1    4    4
    Mazda RX4 Wag     21.0   6  160 1.742137 3.90 2.875 17.02  0  1    4    4
    Datsun 710        22.8   4  108 1.712589 3.85 2.320 18.61  1  1    4    1
    Hornet 4 Drive    21.4   6  258 1.742137 3.08 3.215 19.44  1  0    3    1
    Hornet Sportabout 18.7   8  360 1.819777 3.15 3.440 17.02  0  0    3    2
    Valiant           18.1   6  225 1.734031 2.76 3.460 20.22  1  0    3    1

My concern is two-fold: 

* Is there an exhaustive list of which `plyr` functions drop `row.names` and which don't? (Personally I hate this feature, but that's only me, and I'd like to avoid those functions that do. At the very least I hope that where possible there would be a `preserve.row.names=FALSE` argument or similar.) 
* Are there *any* other side-effects that risk messing up the original `data.frame`, such as dropping/reordering attributes, etc.? (See http://stackoverflow.com/questions/28774153/what-is-the-safest-way-to-transform-a-sequence-of-variables-in-a-data-frame for some background.)

**Comment by hadley** [comment]
There's not, and there probably never will be, sorry.

**Comment by landroni** [comment]
I see. What about documenting which  `plyr`  functions drop  `row.names`  and which don't? As it is, this seems to be inconsistent...

**Comment by hadley** [comment]
Just assume they never preserve `row.names`, and it's an accident of fate if they do.

**Comment by landroni** [comment]
I see, thanks.
