### ISSUE TITLE
`loop_apply` does not emulate `lapply` with regards to `suppressMessages`

### ISSUE THREAD

**Issue by BrianDiggs** [hadley/plyr#256]
# Summary
The internal plyr function `loop_apply` does not propagate the `suppressMessages` context in the same way that `lapply` does. This will result in messages being emitted if they are created in the looped-on function even if the call to `loop_apply` is wrapped in `suppressMessages`. This was discovered in debugging hadley/ggplot2#1101.

# Example code

```r
mg <- function(i=NULL) {
  message("a message")
  invisible(NULL)
}

mg()
suppressMessages(mg())
plyr:::loop_apply(1, mg)
suppressMessages(plyr:::loop_apply(1, mg))
plyr:::loop_apply(1, function(i) suppressMessages(mg(i)))
lapply(seq_len(1), mg)
suppressMessages(lapply(seq_len(1), mg))
```

# Actual output
```r
> mg()
a message
> suppressMessages(mg())
> plyr:::loop_apply(1, mg)
a message
[[1]]
NULL

> suppressMessages(plyr:::loop_apply(1, mg))
a message
[[1]]
NULL

> plyr:::loop_apply(1, function(i) suppressMessages(mg(i)))
[[1]]
NULL

> lapply(seq_len(1), mg)
a message
[[1]]
NULL

> suppressMessages(lapply(seq_len(1), mg))
[[1]]
NULL
```

# Expected output

As above, except `suppressMessages(plyr:::loop_apply(1, mg))` should not emit the message, just as `suppressMessages(lapply(seq_len(1), mg))` does not.

# Discussion
I don't know if the problem is in `plyr` itself, or in the fact that it calls code which is generated via `Rcpp`, or if it is something that changed in R 3.2.0.

In contrast, `suppressWarnings` does seem to work.

```r
wn <- function(i=NULL) {
  warning("a warning")
  invisible(NULL)
}
suppressWarnings(plyr:::loop_apply(1, wn))
```

gives

```r
> suppressWarnings(plyr:::loop_apply(1, wn))
[[1]]
NULL
```

**Comment by hadley** [comment]
@jjallaire @kevinushey is this related to the recent changes in dealing with error propagation?

**Comment by jjallaire** [comment]
Probably. We don't currently trap messages in our evaluation wrapper (just
errors and warnings).

The last time we changed this code we created a cross-version compatibility
issue (which I'm sure you experienced) so I'm honestly a bit hesitant to go
there again right now.
