### ISSUE TITLE
"loop_apply" not resolved from current namespace when using ddply()

### ISSUE THREAD

**Issue by k0dem0nkey** [hadley/plyr#258]
I get this error intermittently using plyr from CRAN and GitHub with the latest R version (3.2.1).

I say intermittent, because restarting R Studio fixes it for some time, and it also seems somewhat dependent on what (if any) other packages I have loaded besides plyr.

The thread [here](http://r.789695.n4.nabble.com/question-re-error-message-package-error-quot-functionName-quot-not-resolved-from-current-namespace-td4663892.html) regarding a similar error in a different package suggests it is due to a missing **PACKAGE** parameter on the call to **.Call()** in **loop_apply.R**, and indeed adding the parameter fixes the issue for R 3.2.1 (pull request to follow).

Note I have not tested the fix in older versions of R.

**Comment by aadler** [comment]
I started getting this error today. I installed plyr from source into R-devel_2015-10-09 itself compiled from source.

**Comment by aadler** [comment]
I think this was fixed by 3256bb524dbe04982ad54300057dd1e1bf852906
