### ISSUE TITLE
ddply on a POSIXlt variable error

### ISSUE THREAD

**Issue by terrytangyuan** [hadley/plyr#261]
Any one had problem before when using reply to split data frame by a POSXlt variable? It always gives me errors saying dimensions are different. It looks like this variable is of two classes POSXlt and POSXct. However it's only one variable as I can see from View() or head(). This might be the reason for the error. Does the function support this data type? If not, any work around for this?

**Comment by hadley** [comment]
Don't use POSIXlt, they cause a lot of problems. Instead convert to POSIXct
