### ISSUE TITLE
R 3.6.0: .parallel=TRUE failures

### ISSUE THREAD

**Issue by HenrikBengtsson** [hadley/plyr#292]
The following works in R 3.5.2 but gives an error in R 3.6.0:
```r
cl <- parallel::makeCluster(2L)
doParallel::registerDoParallel(cl)
x <- list(1:3, 1:3, 1:3)
y <- plyr::llply(x, stats::quantile, probs=c(0,1), .parallel=TRUE)
```

R 3.5.2:
```r
> y <- plyr::llply(x, stats::quantile, probs=c(0,1), .parallel=TRUE)
Warning messages:
1: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
2: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
```

R 3.6.0:
```r
> y <- plyr::llply(x, stats::quantile, probs=c(0,1), .parallel=TRUE)
Error in do.ply(i) : task 3 failed - "'probs' outside [0,1]"
In addition: Warning messages:
1: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
2: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
```

The error only occurs with `probs=c(0,1)`; when using `probs=0` and `probs=1` separately, it works.

Some trial'n'error troubleshooting:  The following works:

```r
> qq <- function(...) { str(list(...)); quantile(...) }
> parallel::clusterExport(cl, "qq")
> y <- plyr::llply(x, qq, probs=c(0,1), .parallel=TRUE)
```
but if we drop `str(list(...))`, which appear to force evaluation of `...`, it fails:
```r
> qq <- function(...) { quantile(...) }
> parallel::clusterExport(cl, "qq")
> y <- plyr::llply(x, qq, probs=c(0,1), .parallel=TRUE)
Error in do.ply(i) : task 3 failed - "'probs' outside [0,1]"
```

PS. This was detected by the CRAN checks of doFuture where I run tests against plyr with `.parallel=TRUE`.

**Comment by HenrikBengtsson** [comment]
Here's another really peculiar(!) observation; again, in R 3.6.0, same setup:
```r
cl <- parallel::makeCluster(2L)
doParallel::registerDoParallel(cl)
x <- list(1:3, 1:3, 1:3)
y <- plyr::llply(x, stats::quantile, probs=c(0,1), .parallel=TRUE)
## Error in do.ply(i) : task 3 failed - "'probs' outside [0,1]"
```
Now, applying to only two of the three elements of `x`:
```r
> y <- plyr::llply(x[1:2], stats::quantile, probs=c(0,1), .parallel=TRUE)
> str(y)
List of 2
 $ : Named num [1:2] 1 3
  ..- attr(*, "names")= chr [1:2] "100%" "300%"
 $ : Named num [1:2] 1 3
  ..- attr(*, "names")= chr [1:2] "100%" "300%"
```
the error goes away, but look at quantile names - "100%" and "300%".   These appear to be based on `seq_along(x)`, because:
```r
> y <- plyr::llply(list(4:9, 4:9), stats::quantile, probs=c(0,1), .parallel=TRUE)
> str(y)
List of 2
 $ : Named num [1:2] 4 9
  ..- attr(*, "names")= chr [1:2] "100%" "600%"
 $ : Named num [1:2] 4 9
  ..- attr(*, "names")= chr [1:2] "100%" "600%"
```
and
```r
> y <- plyr::llply(x[1:2], stats::quantile, probs=c(0.25,0.75), .parallel=TRUE)
> str(y)
List of 2
 $ : Named num [1:2] 1.5 2.5
  ..- attr(*, "names")= chr [1:2] "150%" "250%"
 $ : Named num [1:2] 1.5 2.5
  ..- attr(*, "names")= chr [1:2] "150%" "250%"
```

**Comment by HenrikBengtsson** [comment]
Here's another example illustrating my concern that, when R 3.6.0 comes around, `.parallel=FALSE` and `.parallel=TRUE` might all of a sudden produce different results although there will be no error signalled:

```r
> getRversion()
[1] ‘3.6.0’
> cl <- parallel::makeCluster(1L)
> doParallel::registerDoParallel(cl)
> y0 <- plyr::llply(list(1:10), quantile, probs = (1:3)/4, .parallel = FALSE)
> y1 <- plyr::llply(list(1:10), quantile, probs = (1:3)/4, .parallel = TRUE)
Warning messages:
1: In setup_parallel() : No parallel backend registered
2: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
3: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
 
> y0
[[1]]
 25%  50%  75% 
3.25 5.50 7.75 

> y1
[[1]]
325% 550% 775% 
3.25 5.50 7.75 
```
Note the different names attributes.  In R 3.5.2, we have that `identical(y1, y0)`.


```
> sessionInfo()
R Under development (unstable) (2019-03-09 r76216)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS: /home/hb/software/R-devel/trunk/lib/R/lib/libRblas.so
LAPACK: /home/hb/software/R-devel/trunk/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0    plyr_1.8.4        parallel_3.6.0    Rcpp_1.0.0       
[5] codetools_0.2-16  doParallel_1.0.14 iterators_1.0.10  foreach_1.4.4    
```

**Comment by HenrikBengtsson** [comment]
# Some observations for troubleshooting

I discovered this issue because it triggered [CRAN check errors on my doFuture package](https://cran.r-project.org/web/checks/check_results_doFuture.html).  I noticed them about 7-14 days ago, but they might have been there earlier.  _Comment_: There is one R-devel machines does _not_ give this error, but it could be because it does not have 'plyr' on `R_LIBS`/`.libPaths()` resulting in the `llply(x, quantile, probs = (1:3) / 4, .parallel = TRUE)` to be skipped.  

I think it would be useful to narrow down at which R-devel commit this error was introduced.  A lower bound should be R-devel from 2019-01-07, which was the date doFuture 0.7.0 was submitted to CRAN.
If you guys can narrow down when this occurred, I can help out and study the code to see what updates might cause this.

**Comment by ltierney** [comment]
Looks like a bug I introduced in r75916. Fixed in r76227.

**Comment by HenrikBengtsson** [comment]
Thank you @ltierney. I can confirm that it is fixed in [r76227](https://github.com/wch/r-source/commit/1d0d7e94bed756d1df137f92eb5a664627427ca5):
```r
$ R --vanilla
R Under development (unstable) (2019-03-12 r76227) -- "Unsuffered Consequences"

> cl <- parallel::makeCluster(1L)
> doParallel::registerDoParallel(cl)
> y0 <- plyr::llply(list(1:10), quantile, probs = (1:3)/4, .parallel = FALSE)
> y1 <- plyr::llply(list(1:10), quantile, probs = (1:3)/4, .parallel = TRUE)
Warning messages:
1: In setup_parallel() : No parallel backend registered
2: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
3: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’

> identical(y1, y0)
[1] TRUE

> y0
[[1]]
 25%  50%  75% 
3.25 5.50 7.75
```

@hadley, for the future, do you have any package tests where you test with `.parallel=TRUE`?  If not, I think it would be useful to add a few that uses `cl <- parallel::makeCluster(1L); doParallel::registerDoParallel(cl)`.  Don't just use `doParallel::registerDoParallel(2L)` because that'll use _forked_ processes which will not catch errors related to exporting globals.

_Comment_: The bug in [r75916](https://github.com/wch/r-source/commit/e74759a23d29889ca0011455fb7438ae6aba7c95) was introduced on 2018-12-28. My doFuture 0.7.0 submission was on 2019-01-07 but was not caught by the CRAN incoming.  But looking at my test scripts, I realize that those "extra" tests on plyr are only run if plyr is installed, which it might not be.  Some of the CRAN servers have it when testing doFuture but not incoming.  (I do not list plyr etc. as dependencies on purpose because there's nothing in the doFuture itself that need those and I don't want to enforce lots of dependencies when people install with `dependences=TRUE`)

**Comment by hadley** [comment]
@HenrikBengtsson adding tests seems fairly low priority to me, since plyr is not changing at all.

There are tests, but they are skipped on CRAN: https://github.com/hadley/plyr/blob/master/tests/testthat/test-parallel.r
